## Basic Configuration

baseurl = "/"
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Tomasz Niedziela-Brach"
title = "Tomasz Niedziela-Brach"

theme = "hugo-goa"

## Hugo Built-in Features
# disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Tomasz Niedziela-Brach"
intro = "Web applications engineer"
description = "Designing and building server-side web apps and services. Creating clean and scalable systems. Writing about coding | coding real-world solutions."
authorimage = "tnb-300x300.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Software Developer personal page and blog"
keywords = "dev,coder,python,backend,web,sass,cloud,architecture,code,snippets"

## Social Accounts
[params.social]
github = "tsunday"
instagram = "tomek.niedziela"
linkedin = "niedzielabrach"
twitter = "tomekniedziela"
email = "tomasz@tnbcode.pl"
stackoverflow = "7513751"

## Extras
[params.extra]
copyright = "© 2021. Tomasz Niedziela-Brach. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)."
poweredby = false
highlightjs = true
socialmarkup = true
toc = true
displayrssicon = false

## Main Menu
[[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/about/"
[[menu.main]]
    name = "contact"
    identifier = "contact"
    weight = 300
    url = "/contact/"
